export const API = {
  LOGIN: "/api/v1/user/login",
  GET_MY_KEY: "/api/v1/pki/getMyKey",
  MY_INFO: "/api/v1/user/myInfo",
  UPDATE_MY_INFO: "/api/v1/user/updateMyInfo",
  USER_CHANGE_PASSWORD: "/api/v1/user/changePassword",
  PREVIEW_ID: "/api/images/{0}",
  UPDATE_KEY: "/api/v1/pki/updateTitle/{0}",
  CREATE_KEY: "/api/v1/pki/createNew",
  DELETE_KEY: "/api/v1/pki/revoke",
  GET_ALL_ORG: "/api/v1/org/getOrg?page={0}&limit={1}{2}",
  GET_ALL_USER: "/api/v1/user/getUserPagination?page={0}&limit={1}{2}",
  CREATE_ORG: "/api/v1/org/deleteOrg/{0}",
  EDIT_ORG: "/api/v1/org/editOrg/{0}",
  CREATE_ORG: "/api/v1/org/createNewOrg",
  DELETE_ORG: "/api/v1/org/deleteOrg/{0}",
  CREATE_USER: "/api/v1/user/register",
  UPDATE_USER: "/api/v1/user/updateUser/{0}",
  DELETE_USER: "/api/v1/user/deleteUser/{0}",
};

