export const URL = {
  LOGIN: "/login",
  MENU: {
    DASHBOARD: "/",
    DANH_MUC: "/danh-muc",
    DON_VI: "/don-vi",
    KHOI_PHUC_TAI_KHOAN: "/khoi-phuc-tai-khoan",
    QUAN_LY_NGUOI_DUNG: "/quan-ly-nguoi-dung",
    USER: "/quan-ly-nguoi-dung",
    ROLE: "/vai-tro",
    DU_LIEU_BO_SUNG: "/du-lieu-bo-sung",
    SETTING: "/cai-dat",
    QUAN_LY_TO_CHUC: "/quan-ly-don-vi",
    QUAN_LY_THEM_MOI: "/quan-ly-them-moi",
    THEM_MOI_CHUYEN_NHUONG: "/them-moi-chuyen-nhuong",
    QUAN_LY_CHUYEN_NHUONG: "/quan-ly-chuyen-nhuong",
    QUAN_LY_CAP_LAI: "/quan-ly-cap-lai",
    TRUY_XUAT_KHU_DAT: "/truy-xuat-khu-dat",
  },
  THEM_MOI_GIAY_TO_ID: "/chi-tiet-giay-to/{0}",
  THEM_MOI_GIAY_TO: "/them-moi-giay-to",
  THONG_TIN_CA_NHAN: "/thong-tin-ca-nhan",
  RESET_PASSWORD: "/reset-password",
  TRUY_XUAT_KHU_DAT_ID: "/truy-xuat-khu-dat/{0}",
  FORGET_PASSWORD: "/forget-password",
  THEM_MOI_CHUYEN_NHUONG_ID: "/chi-tiet-chuyen-nhuong/{0}",
  THEM_MOI_CAP_LAI: "/them-moi-cap-lai",
  THEM_MOI_CAP_LAI_ID: "/chi-tiet-cap-lai/{0}",

  DOCS_VIEWER: `https://docs.google.com/viewer?url=${window.location.origin}{0}&embedded=true`,
};

